### ISSUE TITLE
Error while capturing frame: invalid data

### ISSUE THREAD

**Issue by sh4rkman** [WilliamVenner/squad-mortar-helper#2]
Can't get this to work : frame capture doesn't work
No other message are show in logs

OS: W11
Fullscreen, 2540x1080, tried windowed 1920x1080 for the same result

![INLBtg3itA](https://user-images.githubusercontent.com/9033912/170667537-0b8d7db8-2870-4440-afba-12deaf57e9a7.jpg)

**Comment by WilliamVenner** [comment]
Should be fixed in the next release
