### ISSUE TITLE
Error using GPU vision

### ISSUE THREAD

**Issue by automlboss** [WilliamVenner/squad-mortar-helper#3]
Getting this on the latest version. Side question, do height maps need to be selected every map?

[INFO] [smh_vision_ocr] Initializing Tesseract OCR version v5.1.0
[INFO] [smh_web] WebServer listening on 0.0.0.0:58533
[INFO] [smh_web] HTTP server listening on 0.0.0.0:58534
[WARN] [smh_web] Error getting local IP address: The current platform: `windows`, is not suppported
[INFO] [smh_web::http] HTTP connection opened with: 192.168.0.15:58548
[INFO] [smh_web::ws] WebSocket Connection opened with: 192.168.0.15:58549
[ERROR] [smh::vision::hardware::gpu_support] Error loading GPU vision: LoadLibraryExW failed

Caused by:
    The specified module could not be found. (os error 126)

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: BaseThreadInitThunk
   7: RtlUserThreadStart

Falling back to CPU vision...

**Comment by WilliamVenner** [comment]
Please make sure you have extracted the files correctly, `smh.exe` won't work alone, it needs to have `smh_vision_gpu.dll` in the same folder.

Height maps don't need to be selected for every map but it is recommended that you do for maximum accuracy.

**Comment by WilliamVenner** [comment]
By the way,

[WARN] [smh_web] Error getting local IP address: The current platform: windows, is not suppported

Is just a really bad error message: https://github.com/EstebanBorai/local-ip-address/blob/401017ce8b268fe279d67c61e63459bf9314c1cf/src/lib.rs#L115

Windows is definitely supported, it just failed for some other reason.

**Comment by elliottpalermo** [comment]
I'm seeing the same issue as well. I've double checked that everything is exacted correctly.

```
[ERROR] [smh::vision::hardware::gpu_support] Error loading GPU vision: LoadLibraryExW failed

Caused by:
    The specified module could not be found. (os error 126)

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: BaseThreadInitThunk
   7: RtlUserThreadStart

Falling back to CPU vision...
```

Operating System: Windows 10 Home 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
Processor: AMD Ryzen 7 2700X Eight-Core Processor          (16 CPUs), ~3.7GHz
Memory: 32768MB RAM
Card name: NVIDIA GeForce RTX 3080 Ti

**Comment by WilliamVenner** [comment]
Can you try running as administrator? And can I see a screenshot of the file structure?

**Comment by WilliamVenner** [comment]
Personally I am unable to reproduce the issue

![image](https://user-images.githubusercontent.com/14863743/172027318-30b28fdd-478a-4576-8266-e09f1b650d03.png)

**Comment by elliottpalermo** [comment]
![image](https://user-images.githubusercontent.com/14828377/172028177-c3ad82dc-c801-4264-a4aa-a4132442d99a.png)

Tried running as administrator as well -- no dice. To confirm -- it is not necessary to install the CUDA development library from nvidia just to execute, right?

**Comment by WilliamVenner** [comment]
It shouldn't be necessary, but could you try installing it to see if that's the issue?

**Comment by elliottpalermo** [comment]
Looks like it might have done the trick. 

![image](https://user-images.githubusercontent.com/14828377/172029035-d9c43f15-0904-45a8-874c-432190b5ef23.png)

Full disclosure I was also in the middle of following instructions for building it locally so I had installed some of the dependencies with vcpkg as well but that was in a different repository/location on my PC. 

After I saw your last comment I went back to the files I got from github ( c:\squad-mortar-helper ) and was able to run the executable.

**Comment by automlboss** [comment]
Nice call [WilliamVenner](https://github.com/WilliamVenner) & [elliottpalermo](https://github.com/elliottpalermo). Tried running as administrator but that didn't work, tried installing vcpkg/leptonica and that didn't work either. Installing the CUDA toolkit however did work and now the GPU is initializing again. Didn't need the toolkit for previous versions.
